{
 "title": "food_order_assistant_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Feedback +1/-1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(feedback) FROM feedback LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Asking",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM conversations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Relevance",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(relevance) FROM conversations GROUP BY relevance LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(response_time) FROM conversations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Conversation History",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT question, answer, relevance, \"timestamp\" FROM conversations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Open API Cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT openai_cost FROM conversations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total token",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total_tokens FROM conversations LIMIT 50 "
    }
   ]
  }
 ]
}